// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stwbuzktqdnvlgmtmqhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0d2J1emt0cWRudmxnbXRtcWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NDY5OTMsImV4cCI6MjA3MDAyMjk5M30.hNTJqqQofgOyv1LBX5F-_wbnH0vQ1jcyOHQo5ZgDpYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});